version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    # Dla przykładu, backend może być budowany osobno lub korzystać z gotowego obrazu
    image: frontend-ebiznes:latest
    ports:
      - "8080:8080"
