version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/data:/app/data # Miejsce na plik SQLite
    environment:
      - GIN_MODE=release
      - DB_FILE=/app/data/app.db # Ścieżka do pliku SQLite

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
