# This workflow builds and pushes backend and frontend images to Azure Container Registry,
# then deploys them to two separate Azure Web Apps for Containers.

name: Build and deploy containers to Azure Web Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ebizneswojciechp6.azurecr.io
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_09BF61663C474A3D83B14DA1DBDE3D71 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_201D799E4F994B2A8193360B3111C34D }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: cloud/backend
          push: true
          tags: ebizneswojciechp6.azurecr.io/ebiznes-backend:${{ github.sha }}
          file: cloud/backend/Dockerfile

      - name: Build and push frontend image
        uses: docker/build-push-action@v3
        with:
          context: cloud/frontend
          push: true
          tags: ebizneswojciechp6.azurecr.io/ebiznes-frontend:${{ github.sha }}
          file: cloud/frontend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ebiznes-backend-wp6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A00832C1EB5B4F07951385C97D320DFF }}
          images: 'ebizneswojciechp6.azurecr.io/ebiznes-backend:${{ github.sha }}'

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ebiznes-frontend-wp6'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CF1BBCC5338A439BB7712387C49C93C3 }}
          images: 'ebizneswojciechp6.azurecr.io/ebiznes-frontend:${{ github.sha }}'
